name: build and deploy

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - uses: actions/setup-node@master
      with:
        node-version: '13.x'

    - name: install dependencies
      run: |
        npm install

    - name: build website
      run: |
        npm run build

    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:nick-wylynko
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
