name: build and deploy

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - uses: actions/setup-node@master
      with:
        node-version: '13.x'

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:nick-wylynko
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
