name: test

on:
  push:
    branches:    
      - '*' 

jobs:
  test:
    
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@master
        with:
          node-version: '13.x'

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn test